DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  img_screenshot VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);
