DROP TABLE IF EXISTS details CASCADE;
CREATE TABLE details (
  id SERIAL PRIMARY KEY NOT NULL,
  point_id INTEGER REFERENCES points(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  img_of_place VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to labber;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to labber;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to labber;
